Repository prisma-labs/nexus-prisma, pull requests merged in 2019-10, with the labels that each got.

#433 chore: refactor builder to simplify mental model
  src/builder.ts
  src/dmmf/DMMFClass.ts
  src/dmmf/transformer.ts
  src/mapping.ts
  src/publisher.ts
  src/supported-ops.ts
  src/typegen.ts
  src/utils.ts
  tests/__app/generated/nexus-types-prisma.d.ts
  tests/__snapshots__/app.test.ts.snap
  tests/__snapshots__/enums.test.ts.snap
Labels: type/refactor

#441 fix(publishing): publish dmmf objects
  src/publisher.ts
  src/utils.ts
  tests/__app/generated/nexus-types-core.d.ts
  tests/__app/generated/schema.graphql
  tests/__app/main.ts
  tests/__snapshots__/app.test.ts.snap
Labels: impact/high, scope/publishing, type/bug

#454 fix(typegen): delete prev file before writing next
  src/typegen.ts
  src/utils.ts
Labels: scope/typegen, type/bug

#451 fix: publish object types that don't map to prisma models…
  src/publisher.ts
  tests/__utils.ts
  tests/outputs.test.ts
Labels: scope/publishing, type/bug

#452 fix: only publish non-null list + list members
  package.json
  src/builder.ts
  tests/__app/generated/nexus-typegen.d.ts
  tests/__app/generated/schema.graphql
  tests/__snapshots__/app.test.ts.snap
  tests/__snapshots__/enums.test.ts.snap
Labels: scope/publishing, type/bug

#456 feat(typegen): NEXUS_SHOULD_GENERATE_ARTIFACTS env var
  src/builder.ts
Labels: scope/typegen, type/feature

#487 fix: publish scalars from input types
  .gitignore
  src/publisher.ts
  src/utils.ts
  tests/__snapshots__/outputs.test.ts.snap
  tests/outputs.test.ts
Labels: scope/publishing, type/bug

#434 feat: turn into nexus plugin
  README.md
  examples/blog/README.md
  examples/blog/package.json
  examples/blog/src/schema.graphql
  examples/blog/src/schema/index.ts
  examples/blog/tsconfig.json
  examples/blog/yarn.lock
  examples/hello-world/README.md
  examples/hello-world/app.ts
  examples/hello-world/package.json
  examples/hello-world/src/context.ts
  examples/hello-world/src/main.ts
  examples/hello-world/src/schema.ts
  examples/hello-world/src/types.ts
  examples/hello-world/tsconfig.json
  examples/hello-world/yarn.lock
  package.json
  src/builder.ts
  src/dmmf/DMMFClass.ts
  src/index.ts
  src/publisher.ts
  src/utils.ts
  tests/__utils.ts
  tests/app.test.ts
  yarn.lock
Labels: type/feature
