Repository prisma-labs/nexus-prisma, pull requests merged in 2020-01, with the labels that each got.

#577 docs: mention the nexus ver ceiling for 0.3.x
  README.md
Labels: type/docs

#580 feat: support Prisma 2 preview 20
  README.md
  examples/blog/package.json
  examples/blog/prisma/dev.db
  examples/blog/prisma/fake-data.ts
  examples/blog/prisma/migrations/20191004133126-init/README.md
  examples/blog/prisma/migrations/20191004133126-init/schema.prisma
  examples/blog/prisma/migrations/20191004133126-init/steps.json
  examples/blog/prisma/migrations/20191004153921-post-status/README.md
  examples/blog/prisma/migrations/20191004153921-post-status/schema.prisma
  examples/blog/prisma/migrations/20191004153921-post-status/steps.json
  examples/blog/prisma/migrations/20191004154333-author-to-user/README.md
  examples/blog/prisma/migrations/20191004154333-author-to-user/steps.json
  examples/blog/prisma/migrations/20191005224939-default-view-count/README.md
  examples/blog/prisma/migrations/20191005224939-default-view-count/schema.prisma
  examples/blog/prisma/migrations/20191005224939-default-view-count/steps.json
  examples/blog/prisma/migrations/20200122141402-init/README.md
  examples/blog/prisma/migrations/20200122141402-init/schema.prisma
  examples/blog/prisma/migrations/20200122141402-init/steps.json
  examples/blog/prisma/migrations/lift.lock
  examples/blog/prisma/schema.prisma
  examples/blog/src/context.ts
  examples/blog/src/schema/Query.ts
  examples/blog/src/schema/index.ts
  examples/blog/yarn.lock
  examples/hello-world/app.ts
  examples/hello-world/package.json
  examples/hello-world/schema.prisma
  examples/hello-world/yarn.lock
  package.json
  src/builder.ts
  src/dmmf/DmmfTypes.ts
  src/dmmf/transformer.ts
  src/dmmf/utils.ts
  src/index.ts
  src/typegen.ts
  src/utils.ts
  tests/__app/generated/nexus-prisma-typegen.d.ts
  tests/__app/generated/nexus-typegen.d.ts
  tests/__app/generated/schema.graphql
  tests/__app/schema.prisma
  tests/__ensure-engine.ts
  tests/__snapshots__/app.test.ts.snap
  tests/__snapshots__/computedInputs.test.ts.snap
  tests/__snapshots__/enums.test.ts.snap
  tests/__snapshots__/filtering-ordering.test.ts.snap
  tests/__snapshots__/naming.test.ts.snap
  tests/__snapshots__/outputs.test.ts.snap
  tests/__utils.ts
  tests/app.test.ts
  yarn.lock
Labels: note/breaking-change, type/feature

#585 fix(deps): nexus as peer dep, caret-pin @prisma/client
  package.json
  yarn.lock
Labels: scope/deps, type/bug

#590 fix: support id fields not called id
  package.json
  src/builder.ts
  tests/__client-test-context.ts
  tests/__utils.ts
  tests/computedInputs.test.ts
  tests/custom_id.test.ts
  tests/enums.test.ts
  tests/filtering-ordering.test.ts
  tests/hooks.test.ts
  tests/naming.test.ts
  tests/outputs.test.ts
  yarn.lock
Labels: type/bug

#593 docs: update examples
  examples/blog/package.json
  examples/blog/yarn.lock
  examples/hello-world/dev.db
  examples/hello-world/migrations/20200130122322-init/README.md
  examples/hello-world/migrations/20200130122322-init/schema.prisma
  examples/hello-world/migrations/20200130122322-init/steps.json
  examples/hello-world/migrations/lift.lock
  examples/hello-world/package.json
  examples/hello-world/yarn.lock
Labels: type/docs
